### PR TITLE
Add obs4MIPs support

### PR DESCRIPTION
**Pull request by lee1043**
Add obs4MIPs class in projects.py to address https://github.com/esgf2-us/intake-esgf/issues/65

### CODE REVIEW

**Comment by nocollier** [comment]
Thanks for this, I will take a look as soon as I can!

**Review by mgrover1 — CHANGES_REQUESTED** [review]
Thanks for the contribution here @lee1043 ! Do you have any tests that could be added or sample datasets we could use for continuous integration?

**Comment by nocollier** [comment]
This is going to take a little more work. The project object requires you to return certain facets that function in particular ways (like `source_id` is really about the model). However, obs4MIPs doesn't have some of those facets (like a variant) and so this will break some functionality in the catalog. I haven't thought about what to do if certain facets just aren't there. I hear you and will get on this soon.

**Comment by durack1** [comment]
> Thanks for the contribution here @lee1043 ! Do you have any tests that could be added or sample datasets we could use for continuous integration?

@mgrover1 these data are available on obs4MIPs, which I *think* are being replicated across the ALCF and OLCF nodes - we might need to make sure this is the case!

**Comment by nocollier** [comment]
Hey @durack1, thanks for that info. This is not the case currently but there are plans to do so. 

I found some time to sort out what we needed to support this  (and another) project. It is in #75 and should be in main soon. Thanks for the submission @lee1043

**Pull request closed without merging**
